apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatscrm-deployment
  labels:
    app: chatscrum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatscrum
  template:
    metadata:
      labels:
        app: chatscrum 
    spec:
      containers:
      - name: nodeserver
        image: bustopsy777/chatscrum:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: chatscrum-service
spec:
  selector:
    app: chatscrum 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
