apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cs
  name: cs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cs
        tier: frontend
    spec:
      containers:
        - image: jerito1/chatscrum:dev
          imagePullPolicy: Always
          name: cs
          ports:
            - containerPort: 5100
              protocol: TCP
            - containerPort: 5000
              name: cs
              protocol: TCP
          volumeMounts:
            - mountPath: /web/www/Django/ScrumMaster/settings.ini
              name: lj-settings
              subPath: settings_cs.ini
            - mountPath: /web/www/Django/ScrumMaster/ScrumMaster/settings.py
              name: lj-settings
              subPath: settings_cs.py
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /opt/dockermounts
            type: DirectoryOrCreate
          name: lj-settings
