apiVersion: v1
kind: Service
metadata:
  name: cs
  labels:
    app: cs
spec:
  selector:
     app: cs
  type: NodePort
  ports:
     - name: port1
       port: 5100
       targetPort: 5100
       nodePort: 31510
     - name: port2
       port: 5000
       targetPort: 5000
       nodePort: 31500
