apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        tier: frontend
    spec:
      containers:
      - image: {{.Values.deployment.image }}:{{ .Values.deployment.tag }}
        imagePullPolicy: Always
        name: {{ .Values.name }}
        ports:
        - containerPort: 5100
          protocol: TCP
        - containerPort: 5000
          name: {{ .Values.name }}
          protocol: TCP
        volumeMounts:
        - mountPath: /web/www/Django/ScrumMaster/settings.ini
          name: lj-settings
          subPath: settings_cs.ini
        - mountPath: /web/www/Django/ScrumMaster/ScrumMaster/settings.py
          name: lj-settings
          subPath: settings_cs.py
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /opt/dockermounts
          type: Directory
        name: lj-settings
