apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
     app: {{ .Values.name }}
  type: NodePort
  ports:
     - name: port1
       port: 5100
       targetPort: 5100
       nodePort: 31510
     - name: port2
       port: 5000
       targetPort: 5000
       nodePort: 31500
