apiVersion: v1
kind: Service
metadata:
  labels:
    app: wt
  name: {{ .Values.database }}
spec:
  clusterIP: None
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: wt
    tier: mysql
  sessionAffinity: None
  type: ClusterIP
