deployment:
  image: "jerito1/chatscrum"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"
name: "cs-stage"

database:
  name: "wt-mysql-stage"
